/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unicam.cs.pa.jbudget105101;

import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.logging.FileHandler;
import java.util.logging.Logger;

import it.unicam.cs.pa.jbudget105101.view.View;
import it.unicam.cs.pa.jbudget105101.view.ViewJavaFXJBudget;

public class App {

	public final View view;
	public static Logger logger = Logger.getLogger("it.unicam.cs.pa.jbudget105101.App");
	private final static Path path = Paths.get(System.getProperty("user.dir"),"resources", "logs", "AppLog%u.log");

	public App(View view) {
		logger.config("Inizializzo App");
		this.view = view;
	}

	private static void settingsLogger() {
		logger.config("Inizializzo Logger");
		try {
			FileHandler handler = new FileHandler(path.toString());
			logger.addHandler(handler);
		} catch (SecurityException | IOException e) {
			App.logger.config(e.getMessage());
		}
		
	}

	public static void main(String[] args) throws IOException {
		settingsLogger();
		createApp(args).startApp();

	}

	private static App createApp(String[] args) {
		return new App(new ViewJavaFXJBudget());
	}

	private void startApp() throws IOException {
		logger.info("Application started.");
		view.open();
		logger.info("Application terminated.");
	}


	public static double round(double value) {
		logger.config("Utilizzo round");
		return Math.round(value * 100.0) / 100.0;
	}

}
